version: '3.8'

services:
  app:
    image: rebachi/stockcalc:latest
    ports:
      - "5000:5000"
    environment:
      DB_USER: "admin"
      DB_PASSWORD: "Omer1708"
      DB_NAME: "crypto"
      DB_HOST: "crypto.cnuaa2aqad3k.eu-north-1.rds.amazonaws.com"
      DB_PORT: "3306"
      SECRET_KEY: "your_generated_secret_key_here"
    restart: always