"""Add symbol column to trades table

Revision ID: c6443a05d781
Revises: 
Create Date: 2024-11-28 12:11:50.415136

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c6443a05d781"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stocks")
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.add_column(sa.Column("symbol", sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_column("symbol")

    op.create_table(
        "stocks",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("symbol", mysql.VARCHAR(length=10), nullable=False),
        sa.Column("quantity", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "purchase_price", mysql.DECIMAL(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "date_added",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="stocks_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
